

/*
 * Filename: swc_joystick.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_joystick.h"



/* USER CODE START SWC_JOYSTICK_INCLUDE */
#include <stdio.h>
/* USER CODE END SWC_JOYSTICK_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_JOYSTICK_USERDEFINITIONS */
SC_ADC_t adc_joystick_x;
static sint8_t so_joystick = 0;
static char joystickString[50] = {0};
/* USER CODE END SWC_JOYSTICK_USERDEFINITIONS */



/*
* component: swc_joystick
* cycletime: 10
* description: Runnable to update the joystick signal using the API pullPort()
* events: 
* name: JOYSTICK_readJoystick_run
* shortname: readJoystick
* signalIN: 
* signalOUT: so_joystick
* task: tsk_io
*/
void JOYSTICK_readJoystick_run(RTE_event ev){
	
	/* USER CODE START JOYSTICK_readJoystick_run */
    
    //UART_Joystick_x_PutString ("In joystick runnable");

    ADC_JoyStick_x_StartConvert();
    //UART_Joystick_x_PutString ("Started Conversion");
    
    RTE_SC_ADC_pullPort(&SO_JOYSTICK_signal);
    
    //if(0 == RTE_SC_ADC_pullPort(&adc_joystick_x))
    //{
        //so_joystick = ADC_JoyStick_x_GetResult8();  //adc_joystick_x.value.adc_output;
    //}
    
    sprintf(joystickString, "%d", SO_JOYSTICK_signal.value.adc_output);
        
    UART_Joystick_PutString(joystickString);
    UART_Joystick_PutString("\r\n");
    CyDelay(500);
    
    //SetEvent(tsk_control, ev_joystick_onData);
    
    /* USER CODE END JOYSTICK_readJoystick_run */
}

/* USER CODE START SWC_JOYSTICK_FUNCTIONS */

/* USER CODE END SWC_JOYSTICK_FUNCTIONS */

