/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ErikaOS_1_ee.h"
#include "ErikaOS_1_ee_tracing.h"
#include "ADC_JoyStick_x.h"
#include "Joystick_Pin_x_aliases.h"
#include "Joystick_Pin_x.h"
#include "Joystick_Pin_y_aliases.h"
#include "Joystick_Pin_y.h"
#include "ADC_JoyStick_y.h"
#include "UART_Joystick.h"
#include "PWM_Engine.h"
#include "Clock_PWM_Engine.h"
#include "Pin_RGB_Green_aliases.h"
#include "Pin_RGB_Green.h"
#include "ADC_JoyStick_x_IRQ.h"
#include "ADC_JoyStick_x_theACLK.h"
#include "ADC_JoyStick_x_Bypass_aliases.h"
#include "ADC_JoyStick_x_Bypass.h"
#include "ADC_JoyStick_y_IRQ.h"
#include "ADC_JoyStick_y_theACLK.h"
#include "UART_Joystick_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

